services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Vich\FtpSyncBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Tests}'