services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Vich\FtpSyncBundle\Command\:
        resource: '../src/Command'
        tags: [ 'console.command' ]