services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    vich_ftp_sync.command.mapping_list_classes:
        class: Vich\FtpSyncBundle\Command\MappingListClassesCommand
        tags: [ 'console.command' ]
        arguments:
            -